import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import './globals.css';
import { Authentication } from "@/context/Authentication";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Message app</title>
        <meta name="description"  />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Authentication>
          {/* <Navbar/> */}
          {/* Your application's main content */}
          {children}
          <Toaster/>
        </Authentication>
      </body>
    </html>
  );
}